name: Build wheels

on:
  workflow_call:
    inputs:
      variants:
        required: true
        type: string
      image-tag:
        required: true
        type: string

jobs:
  build:
    strategy:
      matrix: ${{ fromJSON(inputs.variants) }}
    runs-on: ${{ matrix.runs-on }}
    defaults:
      run:
        shell: bash
    container:
      image: "${{ vars.DOCKER_REGISTRY }}/${{ vars.DOCKER_IMAGE }}-${{ matrix.id }}:${{ inputs.image-tag }}"
      credentials:
        username: ${{ secrets.DOCKER_LOGIN }}
        password: ${{ secrets.DOCKER_CREDENTIALS }}
    steps:
      - uses: actions/checkout@v4
      - name: Check if tests should be run
        id: check_tests
        run: echo "status=${{ matrix.RUN_UNIT_TESTS == 'ON' || matrix.RUN_ACCEPTANCE_TESTS == 'ON' }}" >> $GITHUB_OUTPUT
      - name: "Generate CMAKE_ARGS"
        run: |
          set -x
          CMAKE_ARGS=""
          CMAKE_ARGS="-DENABLE_CUDA=$([ "${{ matrix.VER_CUDA }}" = "" ] && echo OFF || echo ON) $CMAKE_ARGS"
          CMAKE_ARGS="-DENABLE_TORCH=$([ "${{ matrix.VER_TORCH }}" = "" ] && echo OFF || echo ON) $CMAKE_ARGS"
          CMAKE_ARGS="-DENABLE_ONNX=$([ "${{ matrix.VER_ONNXRUNTIME }}" = "" ] && echo OFF || echo ON) $CMAKE_ARGS"
          CMAKE_ARGS="-DENABLE_TESTS=$([ ! ${{ steps.check_tests.outputs.status }} ] && echo OFF || echo ON) $CMAKE_ARGS"
          CMAKE_ARGS="-DPIP_INDEX=${{ matrix.PIP_INDEX }} $CMAKE_ARGS"
          echo "AIMET_CMAKE_ARGS=$CMAKE_ARGS" >> $GITHUB_ENV

          BUILD_TARGETS="${{ matrix.BUILD_TARGETS }}"
          echo "AIMET_BUILD_TARGETS=$BUILD_TARGETS" >> $GITHUB_ENV
      - name: "Exclude Torch libraries from dependencies for manylinux"
        if: matrix.VER_TORCH || matrix.VER_ONNXRUNTIME
        run: |
          . /etc/profile.d/conda.sh
          TORCH_DIR=$(python3 -c 'import torch; print(f"{torch.utils.cmake_prefix_path}/../../lib")')
          MANYLINUX_EXCLUDE_LIBS="$MANYLINUX_EXCLUDE_LIBS $(find $TORCH_DIR -name '*.so*' | xargs -r patchelf --print-soname | xargs -r printf -- '--exclude %s ')"
          set -x
          echo "MANYLINUX_EXCLUDE_LIBS=$MANYLINUX_EXCLUDE_LIBS" >> $GITHUB_ENV
      - name: "Exclude CUDA libraries from dependencies for manylinux"
        if: matrix.VER_CUDA
        run: |
          . /etc/profile.d/conda.sh
          CUDART_DIR=$(python3 -c 'import sysconfig ; from pathlib import Path; print(Path(sysconfig.get_config_var("prefix"), "lib"))')
          MANYLINUX_EXCLUDE_LIBS="$MANYLINUX_EXCLUDE_LIBS $(find $CUDART_DIR -name 'libcu*.so*' -o -name 'libnv*.so*' -o -name 'libnp*.so*' | xargs -r patchelf --print-soname | xargs -r printf -- '--exclude %s ')"
          set -x
          echo "MANYLINUX_EXCLUDE_LIBS=$MANYLINUX_EXCLUDE_LIBS" >> $GITHUB_ENV
      - name: "Exclude libpython libraries from dependencies for manylinux"
        run: |
          . /etc/profile.d/conda.sh
          LIBS_DIR=$(python3 -c 'import sysconfig ; from pathlib import Path; print(Path(sysconfig.get_config_var("prefix"), "lib"))')
          MANYLINUX_EXCLUDE_LIBS="$MANYLINUX_EXCLUDE_LIBS $(find $LIBS_DIR -name 'libpython*.so*' | xargs -r patchelf --print-soname | xargs -r printf -- '--exclude %s ')"
          set -x
          echo "MANYLINUX_EXCLUDE_LIBS=$MANYLINUX_EXCLUDE_LIBS" >> $GITHUB_ENV
      - name: "Build AIMET wheel package"
        run: |
          set -x
          rm -rf build dist
          . /etc/profile.d/conda.sh
          export CMAKE_ARGS="$AIMET_CMAKE_ARGS"
          export SKBUILD_BUILD_TARGETS="$AIMET_BUILD_TARGETS"

          python3 -m build --wheel --no-isolation .
          auditwheel repair --plat manylinux_2_34_x86_64 $MANYLINUX_EXCLUDE_LIBS dist/aimet*.whl

          if [ "${{ matrix.id }}" == "onnx-torch-cpu" ] ; then
            # Unzip aimet*.whl in current directory to upload Docs
            python3 -m pip install -t wheelhouse --no-deps wheelhouse/aimet*.whl
          fi
      - name: "Re-tag aimet-torch wheel files"
        if: matrix.VER_TORCH
        run: |
          set -x
          . /etc/profile.d/conda.sh
          python3 -m pip install --force-reinstall wheel
          wheel tags --remove --python-tag=py38 --abi-tag=none --platform-tag=any wheelhouse/aimet*.whl
          ls -al wheelhouse/
      - name: Upload AIMET wheel file
        uses: actions/upload-artifact@v3
        if: matrix.id != 'onnx-torch-cpu'
        with:
          name: "${{ matrix.id }}-wheel"
          path: |
            wheelhouse/aimet*.whl
          if-no-files-found: error
          retention-days: 30d
      - name: Upload compiled C++ unit tests
        uses: actions/upload-artifact@v3
        if: matrix.id != 'onnx-torch-cpu'
        with:
          name: "${{ matrix.id }}-tests"
          path: build/**/MoDl*Test
          if-no-files-found: error
          retention-days: 1d
      - name: Upload AIMET documentation
        if: matrix.id == 'onnx-torch-cpu'
        uses: actions/upload-artifact@v3
        with:
          name: Docs
          path: wheelhouse/Docs/
          if-no-files-found: error
          retention-days: 30d
      - name: "Build aimet-onnx for Windows (temporary)"
        if: matrix.id == 'onnx-cpu'
        run: |
          set -x
          rm -rf build dist
          . /etc/profile.d/conda.sh
          export CMAKE_ARGS="$AIMET_CMAKE_ARGS"
          export SKBUILD_BUILD_TARGETS="$AIMET_BUILD_TARGETS"

          # Add cmake flags specific to cross compiling for Windows
          # 1. Define CMAKE_TOOLCHAIN_FILE
          export CMAKE_ARGS="$CMAKE_ARGS -DCMAKE_TOOLCHAIN_FILE=mingw.cmake"

          # 2. Disable building test binaries; mingw environment is missing some C++
          #    libraries required for compiling test binaries
          export CMAKE_ARGS="$CMAKE_ARGS -DENABLE_TESTS=OFF"

          # TODO: aimet-onnx for Windows can be only compiled with ORT 1.22
          python3 -m pip install "onnxruntime==1.22.*"
          python3 -m build --wheel --no-isolation .

          # Retag wheel with win_amd64 platform tag
          wheel tags --remove --platform-tag=win_amd64 dist/aimet*.whl
          mv dist/*.whl wheelhouse
      - name: "Upload aimet-onnx for Windows wheel file (temporary)"
        if: matrix.id == 'onnx-cpu'
        uses: actions/upload-artifact@v3
        with:
          name: "${{ matrix.id }}-win-wheel"
          path: |
            wheelhouse/aimet*-win*.whl
          if-no-files-found: error
          retention-days: 30d
