name: Release to AIMET public (callable workflow)

on:

  workflow_call:
    inputs:
      version:
        description: "AIMET version to release"
        required: true
        type: string
      push_to_pypi:
        description: "Push to pypi if true"
        required: false
        type: boolean
        default: false
      push_to_github:
        description: "Push to github (code & release)"
        required: false
        type: boolean
        default: false
      push_docs:
        description: "Puts up a PR on aimet-pages"
        required: false
        type: boolean
        default: false

env:
  PUBLIC_REPO: "quic/aimet"
  REPO_DIR: "aimet-repo"
  DOCS_REPO: "quic/aimet-pages"
  DOCS_REPO_DIR: "aimet-pages-repo"

jobs:
  checklist:
    name: Validate release version
    if: ${{  github.server_url != 'https://github.com' }}
    runs-on: ubuntu-latest
    steps:
      - name: Validate if input version follows semantic versioning
        run: |
          echo Target release branch: ${{ inputs.version }}
          input_version=`echo ${{ inputs.version }} | grep -o '\.' | wc -l`
          if [[ ${input_version} != 2 ]]; then
              echo "Unsupported version format. Got ${{ inputs.version }}, expecting semantic versioning i.e. <major>.<minor>.<patch>"
              echo "Refer to https://semver.org/"
              exit 1
          fi
      - name: Checkout internal repo
        uses: actions/checkout@v4
        with:
          ref: ${{ github.ref_name }}
          path: ${{ env.REPO_DIR }}
          fetch-depth: 0
      - name: Validate if release branch has same version as input version
        run: |
          repo_version=`cat ${{ env.REPO_DIR }}/packaging/version.txt`
          if [[ ${{ inputs.version }} != ${repo_version} ]]; then
            echo "input release version(${{ inputs.version }}) does not match ${{ github.ref_name }} package version(${repo_version})."
            echo "Please update release version in <aimet_repo>/packaging/version.txt"
            exit 1
          fi

  build_wheels_and_test:
    needs: checklist
    name: Run nightly to build wheels and test basic tests
    secrets: inherit
    uses: ./.github/workflows/nightly-pipeline.yml
    with:
      ref_name: ${{ github.ref_name }}

  release_aimet_onnx_to_pypi:
    if: ${{ inputs.push_to_pypi }} == true
    name: "Push AIMET ONNX wheels to PyPI"
    needs: build_wheels_and_test
    uses: ./.github/workflows/pypi-release-pipeline.yml
    with:
      variant-id: onnx-gpu
      deploy: true
      run_unit_tests: true
      run_acceptance_tests: false
    secrets: inherit

  release_aimet_torch_to_pypi:
    if: ${{ inputs.push_to_pypi }} == true
    name: "Push AIMET torch wheels to PyPI"
    needs: build_wheels_and_test
    uses: ./.github/workflows/pypi-release-pipeline.yml
    with:
      variant-id: torch-gpu
      deploy: true
      run_unit_tests: true
      run_acceptance_tests: false
    secrets: inherit

  release_to_github:
    name: "Release AIMET on Github"
    runs-on: ubuntu-latest
    needs: build_wheels_and_test
    # Requires approval to publish wheels to PyPI from aimet-deployers
    environment: prod
    steps:
      - name: Checkout internal repo
        uses: actions/checkout@v4
        with:
          ref: ${{ github.ref_name }}
          path: ${{ env.REPO_DIR }}
          fetch-depth: 0

      - name: Public release branch to public
        run: |
          cd ${{ env.REPO_DIR }}
          git remote add public-origin https://${{ secrets.AIMET_CI }}@github.com/quic/aimet.git
          git push public-origin ${{ github.ref_name }}:${{ github.ref_name }}

      - name: Download artifacts
        uses: actions/download-artifact@v3
        with:
          # Only include (torch|onnx)-(cpu|gpu)-wheel; exclude onnx-cpu-win-wheel
          pattern: "*pu-wheel"
          path: artifacts-downloaded

      - name: Setup GitHub CLI
        run: |
          # Ref: https://github.com/cli/cli/blob/trunk/docs/install_linux.md
          (type -p wget >/dev/null || (sudo apt update && sudo apt-get install wget -y)) \
            && sudo mkdir -p -m 755 /etc/apt/keyrings \
                  && out=$(mktemp) && wget -nv -O$out https://cli.github.com/packages/githubcli-archive-keyring.gpg \
                  && cat $out | sudo tee /etc/apt/keyrings/githubcli-archive-keyring.gpg > /dev/null \
            && sudo chmod go+r /etc/apt/keyrings/githubcli-archive-keyring.gpg \
            && echo "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/githubcli-archive-keyring.gpg] https://cli.github.com/packages stable main" | sudo tee /etc/apt/sources.list.d/github-cli.list > /dev/null \
            && sudo apt update \
            && sudo apt install gh -y

      - name: Release wheels on Github
        if: ${{ inputs.push_to_github }} == true
        env:
          GITHUB_TOKEN: ${{ secrets.AIMET_CI }}
          tag: ${{ inputs.version }}
        run: |
          mkdir assets_to_upload
          # Copy all wheels to upload on release
          find artifacts-downloaded -name "aimet*.whl" -exec cp {} assets_to_upload \;

          export whl_file=$(\
              find assets_to_upload \
              -regextype posix-extended \
              -regex ".*aimet_(torch|onnx)-[0-9]+\.[0-9]+\.[0-9]+\+(cpu|cu).+.whl" \
          )
          # Create release on public repo
          title="Version ${tag}"
          gh release create "${tag}" --repo ${{ env.PUBLIC_REPO }} --target ${{ github.ref_name }} --title "${title}" --generate-notes $whl_file

      - name: Checkout aimet-pages
        if: ${{ inputs.push_docs }} == true
        uses: actions/checkout@v4
        with:
          ref: master
          path: ${{ env.DOCS_REPO_DIR }}
          repository: ${{ env.DOCS_REPO }}
          github-server-url: https://github.com
          token: ${{ secrets.AIMET_CI }}
          fetch-depth: 0

      - name: Put up a PR for new docs
        if: ${{ inputs.push_docs }} == true
        env:
          GITHUB_TOKEN: ${{ secrets.AIMET_CI }}
          tag: ${{ inputs.version }}
        run: |
          # Copy Docs to aimet-pages
          mkdir -p ${{ env.DOCS_REPO_DIR }}/releases/${tag}
          cp -r artifacts-downloaded/Docs/. ${{ env.DOCS_REPO_DIR }}/releases/${tag}

          # Create PR on aimet-pages
          cd ${{ env.DOCS_REPO_DIR }}
          git checkout -b ${{ github.ref_name }}

          # Update latest symlink
          unlink releases/latest || true
          ln -s ${tag} releases/latest

          # Commit doc changes
          git add releases/
          git remote add public-origin https://${{ secrets.AIMET_CI }}@github.com/${{ env.DOCS_REPO }}.git
          git config user.email "aimetci@quicinc.com"
          git config user.name "AIMET CI"
          git commit -m "Release docs ${tag}" -s

          # TODO: for point-releases, consider adding -f
          git push public-origin ${{ github.ref_name }}

          # Create PR on quic/aimet-pages
          gh pr create --repo ${{ env.DOCS_REPO }} --base master --head ${{ github.ref_name }} --title "Release ${tag}" --body "Release docs for ${tag}"

  notify_release_on_slack:
    name: Announce release on internal channels
    needs: [ release_aimet_torch_to_pypi, release_aimet_onnx_to_pypi, release_to_github ]
    runs-on: ubuntu-latest
    steps:
      - uses: slackapi/slack-github-action@v1.25.0
        with:
          channel-id: C0898PQVA31,C02TLE1KJ3B # channel ids in order: aimet, general
          slack-message: ":rocket: *AIMET ${{ inputs.version }} released* :tada: \n *PyPI*\n- AIMET-ONNX: https://pypi.org/project/aimet-onnx/ \n- AIMET-TORCH: https://pypi.org/project/aimet-torch/ \n\n *Github*: https://github.com/quic/aimet/releases \n *Docs*: https://quic.github.io/aimet-pages/releases/latest/index.html \n"
        env:
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_NOTIFIER_TOKEN }}
