name: Run acceptance tests

on:
  workflow_call:
    inputs:
      variants:
        required: true
        type: string

jobs:
  test:
    name: Run AIMET acceptance tests
    strategy:
      fail-fast: false
      matrix: ${{ fromJSON(inputs.variants) }}
    runs-on: ${{ matrix.runs-on }}
    env:
      pytest_github_report: true
      pytest_use_zeros: true
    container:
      image: "ubuntu:22.04"
    steps:
      - if: matrix.ENABLE_TESTS == 'ON'
        run: |
          apt update -qq
          apt install --no-install-recommends -y git curl g++ ca-certificates cmake make
          curl -sSL 'https://pki.qualcomm.com/{qc_root_g2_cert.crt,ssl_v3_cert.crt,ssl_v4_cert.crt}' > qualcomm.crt
          update-ca-certificates
          rm -rf download
      - if: matrix.ENABLE_TESTS == 'ON'
        uses: actions/checkout@v4
      - if: matrix.ENABLE_TESTS == 'ON'
        uses: actions/download-artifact@v3
        with:
          name: "${{ matrix.id }}-wheel"
          path: "downloads"
      - name: Create python virtual environment
        if: ${{ matrix.id  != 'tf-torch-cpu' }}
        uses: ./.github/actions/setup-conda-env
        with:
          ENV_NAME: ${{ matrix.id }}
          VER_PYTHON: ${{ matrix.VER_PYTHON }}
          VER_CUDA: ${{ matrix.VER_CUDA }}
          VER_TORCH: ${{ matrix.VER_TORCH }}
          VER_ONNXRUNTIME: ${{ matrix.VER_ONNXRUNTIME }}
          PIP_INDEX: ${{ matrix.PIP_INDEX }}
      - name: Run acceptance tests
        if: matrix.ENABLE_TESTS == 'ON'
        run: |
          set -x
          if [ "${{ matrix.VER_TENSORFLOW }}" != "" ] ; then
              PYTEST_TARGETS="$PYTEST_TARGETS ./NightlyTests/tensorflow"
              ./.conda/bin/conda run --live-stream --name "${{ matrix.id }}" python3 -m pip install wget
              ./.conda/bin/conda run --live-stream --name "${{ matrix.id }}" python3 ./NightlyTests/tensorflow/dependencies.py ./NightlyTests/tensorflow/resnet50_eval_scores.csv
          elif [ "${{ matrix.VER_ONNXRUNTIME }}" != "" ] ; then
              PYTEST_TARGETS="$PYTEST_TARGETS ./NightlyTests/onnx"
          elif [ "${{ matrix.VER_TORCH }}" != "" ] ; then
              PYTEST_TARGETS="$PYTEST_TARGETS ./NightlyTests/torch"
              ./.conda/bin/conda run --live-stream --name "${{ matrix.id }}" python3 -m pip install wget
              ./.conda/bin/conda run --live-stream --name "${{ matrix.id }}" python3 ./NightlyTests/torch/dependencies.py ./NightlyTests/torch/resnet18_eval_scores.csv
          fi
          PYTEST_ARGS="not blah"
          if [ "${{ matrix.VER_CUDA }}" = "" ] ; then
              PYTEST_ARGS="not cuda"
          fi
          ./.conda/bin/conda run --live-stream --name "${{ matrix.id }}" python3 -m pytest -m "$PYTEST_ARGS" $PYTEST_TARGETS