name: Run Unit and Acceptance tests

on:
  workflow_call:
    inputs:
      variants:
        required: true
        type: string
      force_run_unit_tests:
        required: false
        type: boolean
        default: false
      force_run_acceptance_tests:
        required: false
        type: boolean
        default: false

jobs:
  test:
    name: Run AIMET unit tests
    strategy:
      fail-fast: false
      matrix: ${{ fromJSON(inputs.variants) }}
    runs-on: ${{ matrix.runs-on }}
    env:
      pytest_github_report: true
      pytest_use_zeros: true
    container:
      image: "ubuntu:22.04"
    steps:
      - name: Check if unit tests should be run
        id: check_unit_tests
        run: echo "status=${{ inputs.force_run_unit_tests || matrix.RUN_UNIT_TESTS == 'ON' }}" >> $GITHUB_OUTPUT
      - name: Check if acceptance tests should be run
        id: check_acceptance_tests
        run: echo "status=${{ inputs.force_run_acceptance_tests || matrix.RUN_ACCEPTANCE_TESTS == 'ON' }}" >> $GITHUB_OUTPUT
      - name: Check if any tests should be run
        id: check_tests
        run: echo "status=${{ steps.check_unit_tests.outputs.status || steps.check_acceptance_tests.outputs.status }}" >> $GITHUB_OUTPUT
      - if: ${{ steps.check_tests.outputs.status == 'true' }}
        run: |
          apt update -qq
          apt install --no-install-recommends -y git curl g++ ca-certificates cmake make
          # ref: https://qwiki.qualcomm.com/it-sec-public/QC_SSL#Machines
          curl -L 'https://pki.qualcomm.com/{qc_root_g2_cert.crt,ssl_v3_cert.crt,ssl_v4_cert.crt}' -o '/usr/local/share/ca-certificates/#1'
          update-ca-certificates
          # Update certificate env variables
          echo "REQUESTS_CA_BUNDLE=/etc/ssl/certs/ca-certificates.crt" >> $GITHUB_ENV
          echo "SSL_CERT_FILE=/etc/ssl/certs/ca-certificates.crt" >> $GITHUB_ENV
          rm -rf download
      - if: ${{ steps.check_tests.outputs.status == 'true' }}
        uses: actions/checkout@v4
      - if: ${{ steps.check_tests.outputs.status == 'true' }}
        uses: actions/download-artifact@v3
        with:
          name: "${{ matrix.id }}-wheel"
          path: "downloads"
      - if: ${{ steps.check_tests.outputs.status == 'true' }}
        uses: actions/download-artifact@v3
        with:
          name: "${{ matrix.id }}-tests"
          path: "downloads"
      - name: Create python virtual environment
        if: ${{ matrix.id  != 'onnx-torch-cpu' }}
        uses: ./.github/actions/setup-conda-env
        with:
          ENV_NAME: ${{ matrix.id }}
          VER_PYTHON: ${{ matrix.VER_PYTHON }}
          VER_CUDA: ${{ matrix.VER_CUDA }}
          VER_TORCH: ${{ matrix.VER_TORCH }}
          VER_ONNXRUNTIME: ${{ matrix.VER_ONNXRUNTIME }}
          PIP_INDEX: ${{ matrix.PIP_INDEX }}
      - name: Run pylint
        if: ${{ steps.check_tests.outputs.status == 'true' }}
        run: |
          CONDA_PYTHONPATH="./.conda/envs/${{ matrix.id }}/lib/python${{ matrix.VER_PYTHON }}/site-packages"
          AIMET_PACKAGES=$(find $CONDA_PYTHONPATH -regex ".*/aimet_\(common\|torch\|onnx\)" | tr "\n" " ")

          ./.conda/bin/conda run --live-stream --name "${{ matrix.id }}" \
              python3 -m pylint --rcfile=.pylintrc $AIMET_PACKAGES
      - name: Run Unit tests
        if: ${{ steps.check_unit_tests.outputs.status == 'true' }}
        run: |
          set -x

          for target in $(find downloads -name "*Test"); do
              chmod +x $target
              # NOTE: Set LD_LIBRARY_PATH for dynamic linking with libpython3.so
              #       since ubuntu:22.04 docker image doesn't have built-in libpython3.so
              LD_LIBRARY_PATH=".conda/envs/${{ matrix.id }}/lib" \
                  ./.conda/bin/conda run --live-stream --name "${{ matrix.id }}" $target
          done

          PYTEST_TARGETS="./ModelOptimizations/DlQuantization/test"
          PYTEST_TARGETS="$PYTEST_TARGETS ./TrainingExtensions/common/test"

          if [ "${{ matrix.VER_ONNXRUNTIME }}" != "" ] ; then
              PYTEST_TARGETS="$PYTEST_TARGETS ./TrainingExtensions/onnx/test"
          elif [ "${{ matrix.VER_TORCH }}" != "" ] ; then
              PYTEST_TARGETS="$PYTEST_TARGETS ./TrainingExtensions/torch/test"
          fi
          PYTEST_ARGS="not blah"
          if [ "${{ matrix.VER_CUDA }}" = "" ] ; then
              PYTEST_ARGS="not cuda"
          fi
          ./.conda/bin/conda run --live-stream --name "${{ matrix.id }}" python3 -m pytest -m "$PYTEST_ARGS" $PYTEST_TARGETS
      - name: Run Acceptance tests
        if: ${{ steps.check_acceptance_tests.outputs.status == 'true' }}
        run: |
          set -x
          PYTEST_TARGETS=""
          if [ "${{ matrix.VER_ONNXRUNTIME }}" != "" ] ; then
              PYTEST_TARGETS="$PYTEST_TARGETS ./NightlyTests/onnx"
          elif [ "${{ matrix.VER_TORCH }}" != "" ] ; then
              PYTEST_TARGETS="$PYTEST_TARGETS ./NightlyTests/torch"
              ./.conda/bin/conda run --live-stream --name "${{ matrix.id }}" python3 -m pip install wget
              ./.conda/bin/conda run --live-stream --name "${{ matrix.id }}" python3 ./NightlyTests/torch/dependencies.py ./NightlyTests/torch/resnet18_eval_scores.csv
          fi
          PYTEST_ARGS="not blah"
          if [ "${{ matrix.VER_CUDA }}" = "" ] ; then
              PYTEST_ARGS="not cuda"
          fi
          ./.conda/bin/conda run --live-stream --name "${{ matrix.id }}" python3 -m pytest -m "$PYTEST_ARGS" $PYTEST_TARGETS
